# Generated by Django 5.1.2 on 2024-10-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_parent_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='task_collaborations', to='tasks.user'),
        ),
    ]
