# Generated by Django 5.1.2 on 2024-11-06 05:45
from datetime import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_description_note_content_remove_note_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='task',
        ),
        migrations.AddField(
            model_name='note',
            name='due_date',
            field=models.DateField(default=datetime.date),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='project',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, to='tasks.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.CharField(default=50, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default=50, max_length=100),
            preserve_default=False,
        ),
    ]
