# Generated by Django 5.1.2 on 2024-11-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_note_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
