# Generated by Django 5.1.2 on 2024-11-06 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_note_due_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
